
services:
  frontend:
    build: .
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "5173:5173"  
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:8000/api
    networks:
      - frontend-network
    command: npm run dev -- --host 0.0.0.0

networks:
  frontend-network:
    driver: bridge